language: node_js

node_js:
  - '10'

env:
  global:
  - USER="jimzhan"
  - EMAIL="jim.zhan@me.com"
  - REPO="yo-env"
  - GH_REPO="github.com/${USER}/${REPO}.git"

deploy:
  provider: npm
  email: jim.zhan@me.com
  api_key: $NPM_TOKEN
  on:
    tags: true

before_script:
  - npm install --global makeshift && makeshift -s @bcoe -r registry.npmjs.org

before_install:
 - printf "registry=https://registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

install:
  - npm install

script:
  - npm run test
